services:
  api:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8030:8030'
    volumes:
      - ./app:/app/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: tray_mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3300:3300'

volumes:
  db_data:
